package LinterDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_SiblingsCheckType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_SiblingsCheckType() {
    super(0xc400f4156edc4c5fL, 0xa0ceccbb04f551e6L, 0x7f24bdd32ec5e4f4L, "SiblingsCheckType", "r:21d30a29-243b-40e8-a51d-38ea30739819(LinterDSL.structure)/9161656256698901748", PrimitiveTypeId.STRING);
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_Next_0 = new EnumerationDescriptor.MemberDescriptor("Next", "only have next immediate sibling", "r:21d30a29-243b-40e8-a51d-38ea30739819(LinterDSL.structure)/9161656256698901749", "only have next immediate sibling");
  private final EnumerationDescriptor.MemberDescriptor VALUE_NextAll_0 = new EnumerationDescriptor.MemberDescriptor("NextAll", "only appear before elements", "r:21d30a29-243b-40e8-a51d-38ea30739819(LinterDSL.structure)/9161656256698901753", "only appear before elements");
  private final EnumerationDescriptor.MemberDescriptor VALUE_NextNo_0 = new EnumerationDescriptor.MemberDescriptor("NextNo", "not have next siblings", "r:21d30a29-243b-40e8-a51d-38ea30739819(LinterDSL.structure)/9161656256698901771", "not have next siblings");
  private final EnumerationDescriptor.MemberDescriptor VALUE_Prev_0 = new EnumerationDescriptor.MemberDescriptor("Prev", "only have previous immediate sibling", "r:21d30a29-243b-40e8-a51d-38ea30739819(LinterDSL.structure)/9161656256698901756", "only have previous immediate sibling");
  private final EnumerationDescriptor.MemberDescriptor VALUE_PrevAll_0 = new EnumerationDescriptor.MemberDescriptor("PrevAll", "only appear after elements", "r:21d30a29-243b-40e8-a51d-38ea30739819(LinterDSL.structure)/9161656256698901760", "only appear after elements");
  private final EnumerationDescriptor.MemberDescriptor VALUE_PrevNo_0 = new EnumerationDescriptor.MemberDescriptor("PrevNo", "not have previous siblings", "r:21d30a29-243b-40e8-a51d-38ea30739819(LinterDSL.structure)/9161656256698901765", "not have previous siblings");

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_Next_0, VALUE_NextAll_0, VALUE_NextNo_0, VALUE_Prev_0, VALUE_PrevAll_0, VALUE_PrevNo_0);
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "Next":
        return VALUE_Next_0;
      case "NextAll":
        return VALUE_NextAll_0;
      case "NextNo":
        return VALUE_NextNo_0;
      case "Prev":
        return VALUE_Prev_0;
      case "PrevAll":
        return VALUE_PrevAll_0;
      case "PrevNo":
        return VALUE_PrevNo_0;
    }
    return null;
  }
}
