package LinterDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_CheckType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_CheckType() {
    super(0xc400f4156edc4c5fL, 0xa0ceccbb04f551e6L, 0x1419e78e67916789L, "CheckType", "r:21d30a29-243b-40e8-a51d-38ea30739819(LinterDSL.structure)/1448443353985279881", PrimitiveTypeId.STRING);
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_Error_0 = new EnumerationDescriptor.MemberDescriptor("Error", "Error", "r:21d30a29-243b-40e8-a51d-38ea30739819(LinterDSL.structure)/1448443353985279882", "Error");
  private final EnumerationDescriptor.MemberDescriptor VALUE_Warning_0 = new EnumerationDescriptor.MemberDescriptor("Warning", "Warning", "r:21d30a29-243b-40e8-a51d-38ea30739819(LinterDSL.structure)/1448443353985279883", "Warning");

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return VALUE_Error_0;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_Error_0, VALUE_Warning_0);
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "Error":
        return VALUE_Error_0;
      case "Warning":
        return VALUE_Warning_0;
    }
    return null;
  }
}
