package LinterDSL.textGen;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.internal.collections.runtime.Sequence;

public abstract class Linter_functions {
  public static void toStringArray(Iterable<SNode> children, final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    for (SNode child : Sequence.fromIterable(children)) {
      if (child == Sequence.fromIterable(children).first()) {
        tgs.append("['");
      }
      if (child != Sequence.fromIterable(children).first()) {
        tgs.append("', '");
      }

      tgs.appendNode(child);

      if (child == Sequence.fromIterable(children).last()) {
        tgs.append("']");
      }
    }
  }
}
