package LinterDSL.textGen;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.internal.collections.runtime.Sequence;

public abstract class Linter_functions {
  public static void toStringList(Iterable<SNode> sequence, final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    for (SNode element : Sequence.fromIterable(sequence)) {
      if (element != Sequence.fromIterable(sequence).first()) {
        tgs.append("', '");
      }

      tgs.appendNode(element);
    }
  }
}
